export const SET_CURRENT_SONG = "SET_CURRENT_SONG";
export const SET_CURRENT_PLAYLIST = "SET_CURRENT_PLAYLIST";
export const ADD_TO_PLAYLIST = "ADD_TO_PLAYLIST";
export const REMOVE_TO_PLAYLIST = "REMOVE_TO_PLAYLIST";
